
#!/usr/bin/env python3
"""Incremental CLI reviewer for Trading Paints showroom mapping seeds.

Usage example:
    python tp_seed_review_cli.py --seed tp_showroom_mapping.seed.autopromoted.json

What it does:
- loads an existing TP showroom seed used by Nishizumi Paints
- scans public Trading Paints showroom car pages (Road + Oval)
- scans active iRacing cars from the official iRacing filepath list
- only reviews cars that are NOT already mapped and NOT already marked unsupported
- lets you choose in the console:
    1 = mark unsupported in TP
    2 = accept best match
    3..N = accept another shown candidate
    s = skip for now
    q = save and quit

The seed is updated in place by default and a .bak backup is created once.
"""

from __future__ import annotations

import argparse
import json
import os
import re
import shutil
import sys
import time
from dataclasses import dataclass
from difflib import SequenceMatcher
from pathlib import Path
from typing import Any
from urllib.parse import urlparse

import requests

IRACING_ACTIVE_CARS_URL = (
    "https://support.iracing.com/support/solutions/articles/31000172625-filepath-for-active-iracing-cars"
)
TP_SHOWROOM_ROOTS = (
    "https://www.tradingpaints.com/showroom/Oval",
    "https://www.tradingpaints.com/showroom/Road",
)
APP_USER_AGENT = "nishizumi-tp-seed-review/1.0"
TP_CAR_SHOWROOM_CATEGORIES = {"road", "oval"}


@dataclass
class TPVehicle:
    mid: int
    category: str
    slug: str
    tp_name: str
    showroom_url: str


@dataclass
class IRacingCar:
    iracing_name: str
    filepath_full: str
    directory_leaf: str


def _read_text_source(source: str, timeout: float) -> str:
    if re.match(r"^https?://", source, flags=re.I):
        resp = requests.get(source, timeout=timeout, headers={"User-Agent": APP_USER_AGENT})
        resp.raise_for_status()
        return resp.text
    return Path(source).read_text(encoding="utf-8", errors="replace")


def _read_json_source(source: str) -> Any:
    return json.loads(Path(source).read_text(encoding="utf-8"))


def _safe_json_dump(path: Path, payload: Any) -> None:
    path.parent.mkdir(parents=True, exist_ok=True)
    path.write_text(json.dumps(payload, ensure_ascii=False, indent=2), encoding="utf-8")


def normalize_text(value: str) -> str:
    text = str(value or "").lower()
    text = text.replace("[legacy]", "legacy")
    text = text.replace("&", " and ")
    text = re.sub(r"[^a-z0-9]+", " ", text)
    return " ".join(text.split())


def tokenize(value: str) -> set[str]:
    return set(normalize_text(value).split())


def leaf_from_path(path: str) -> str:
    raw = str(path or "").strip().replace("/", "\\")
    if not raw:
        return ""
    return raw.split("\\")[-1].lower()


def parse_iracing_active_cars(source: str, timeout: float) -> dict[str, IRacingCar]:
    # Accept pre-parsed JSON generated by prior tools.
    if Path(source).exists() and Path(source).suffix.lower() == ".json":
        raw = _read_json_source(source)
        if isinstance(raw, dict) and isinstance(raw.get("cars"), dict):
            result: dict[str, IRacingCar] = {}
            for key, entry in raw["cars"].items():
                if not isinstance(entry, dict):
                    continue
                fp = str(entry.get("filepath_full") or key).replace("/", "\\").strip("\\")
                if not fp:
                    continue
                result[fp.lower()] = IRacingCar(
                    iracing_name=str(entry.get("iracing_name") or fp),
                    filepath_full=fp,
                    directory_leaf=leaf_from_path(fp),
                )
            if result:
                return result

    text = _read_text_source(source, timeout)

    # Try BeautifulSoup when available for more reliable extraction.
    parsed_rows: list[tuple[str, str]] = []
    try:
        from bs4 import BeautifulSoup  # type: ignore

        soup = BeautifulSoup(text, "html.parser")
        for tr in soup.find_all("tr"):
            cells = [c.get_text(" ", strip=True) for c in tr.find_all(["td", "th"])]
            if len(cells) < 2:
                continue
            name = str(cells[0]).strip()
            filepath = str(cells[1]).strip().strip("\\/")
            if "\\" in filepath or re.fullmatch(r"[a-z0-9_\\]+", filepath, flags=re.I):
                parsed_rows.append((name, filepath))
    except Exception:
        pass

    lines: list[str] = []
    if parsed_rows:
        for name, filepath in parsed_rows:
            lines.append(f"{name}\\{filepath}")
    else:
        # HTML-aware fallback preserving line breaks better than raw tag stripping.
        if "<" in text and ">" in text:
            html = text
            html = re.sub(r"(?is)<\s*br\s*/?\s*>", "\n", html)
            html = re.sub(r"(?is)</\s*(p|div|tr|li|h1|h2|h3|h4|h5|h6)\s*>", "\n", html)
            html = re.sub(r"(?is)<[^>]+>", "", html)
            html = html.replace("&nbsp;", " ")
            lines = [line.strip() for line in html.splitlines() if line.strip()]
        else:
            lines = [line.strip() for line in text.splitlines() if line.strip()]

    result: dict[str, IRacingCar] = {}

    # Pattern like: "Acura ARX-06 GTP\acuraarx06gtp" or "Aston Martin DBR9 GT1\astonmartin\dbr9"
    joined = "\n".join(lines)
    pattern = re.compile(
        r"(?P<name>[^\n\\][^\n]*?)\\(?P<path>[A-Za-z0-9_]+(?:\\[A-Za-z0-9_]+)+|[A-Za-z0-9_]+)\s*(?:\n|$)"
    )

    for match in pattern.finditer(joined):
        name = re.sub(r"\s+", " ", match.group("name")).strip(" -\t\r\n")
        filepath = match.group("path").strip("\\")
        if not name or not filepath:
            continue
        # Filter obvious non-car headings/noise.
        if len(filepath) < 2 or normalize_text(name) in {"filepath", "car name", "name"}:
            continue
        result[filepath.lower()] = IRacingCar(
            iracing_name=name,
            filepath_full=filepath,
            directory_leaf=leaf_from_path(filepath),
        )

    if result:
        return result

    raise RuntimeError("No iRacing cars parsed from source")


def parse_tp_showroom_catalog(timeout: float, sleep_seconds: float) -> list[TPVehicle]:
    out: dict[tuple[str, int], TPVehicle] = {}
    link_pattern = re.compile(r"/showroom/(Road|Oval)/(\d+)/([A-Za-z0-9\-\._\(\)]+)", re.I)

    for root in TP_SHOWROOM_ROOTS:
        resp = requests.get(root, timeout=timeout, headers={"User-Agent": APP_USER_AGENT})
        resp.raise_for_status()
        html = resp.text

        vehicles: list[tuple[str, int, str, str]] = []

        try:
            from bs4 import BeautifulSoup  # type: ignore

            soup = BeautifulSoup(html, "html.parser")
            for a in soup.find_all("a", href=True):
                href = str(a.get("href") or "").strip()
                m = link_pattern.search(href)
                if not m:
                    continue
                category = m.group(1)
                mid = int(m.group(2))
                slug = m.group(3)
                tp_name = a.get_text(" ", strip=True) or slug.replace("-", " ")
                vehicles.append((category, mid, slug, tp_name))
        except Exception:
            for m in re.finditer(
                r'href=["\'](?P<href>/showroom/(Road|Oval)/(?P<mid>\d+)/(?P<slug>[A-Za-z0-9\-\._\(\)]+))["\'][^>]*>(?P<label>.*?)</a>',
                html,
                flags=re.I | re.S,
            ):
                category = "Road" if "/Road/" in m.group("href") else "Oval"
                mid = int(m.group("mid"))
                slug = m.group("slug")
                label = re.sub(r"(?is)<[^>]+>", " ", m.group("label"))
                tp_name = " ".join(label.split()) or slug.replace("-", " ")
                vehicles.append((category, mid, slug, tp_name))

        for category, mid, slug, tp_name in vehicles:
            if category.lower() not in TP_CAR_SHOWROOM_CATEGORIES:
                continue
            url = f"https://www.tradingpaints.com/showroom/{category}/{mid}/{slug}"
            key = (category.lower(), mid)
            current = out.get(key)
            if current is None or len(tp_name) > len(current.tp_name):
                out[key] = TPVehicle(
                    mid=mid,
                    category=category,
                    slug=slug,
                    tp_name=tp_name,
                    showroom_url=url,
                )
        if sleep_seconds > 0:
            time.sleep(sleep_seconds)

    return sorted(out.values(), key=lambda v: (v.category.lower(), v.mid, v.slug.lower()))


def score_candidate(car: IRacingCar, tp: TPVehicle) -> float:
    ir_name = normalize_text(car.iracing_name)
    tp_name = normalize_text(tp.tp_name)
    slug_text = normalize_text(tp.slug.replace("-", " "))
    path_text = normalize_text(car.filepath_full.replace("\\", " "))
    leaf_text = normalize_text(car.directory_leaf)

    # Remove legacy noise for core compare.
    ir_core = ir_name.replace("legacy ", "").strip()
    tp_core = tp_name.replace("legacy ", "").strip()

    seq_name = SequenceMatcher(None, ir_core, tp_core).ratio() * 70.0
    seq_slug = SequenceMatcher(None, ir_core, slug_text).ratio() * 20.0
    seq_path = SequenceMatcher(None, path_text, tp_core).ratio() * 10.0

    ir_tokens = tokenize(ir_core) | tokenize(leaf_text)
    tp_tokens = tokenize(tp_core) | tokenize(slug_text)
    overlap = 0.0
    if ir_tokens and tp_tokens:
        overlap = (len(ir_tokens & tp_tokens) / len(ir_tokens | tp_tokens)) * 30.0

    score = max(seq_name + overlap, seq_name + seq_slug, seq_name + seq_path)

    if ir_core == tp_core:
        score = 100.0
    elif leaf_text and leaf_text == normalize_text(tp.slug).replace(" ", ""):
        score = max(score, 97.0)
    elif ir_tokens and tp_tokens and ir_tokens == tp_tokens:
        score = max(score, 96.0)

    return round(min(score, 100.0), 2)


def build_candidates(cars: dict[str, IRacingCar], catalog: list[TPVehicle], top_n: int = 5) -> dict[str, list[dict[str, Any]]]:
    out: dict[str, list[dict[str, Any]]] = {}
    for key, car in cars.items():
        scored: list[tuple[float, TPVehicle]] = []
        for tp in catalog:
            s = score_candidate(car, tp)
            if s >= 35.0:
                scored.append((s, tp))
        scored.sort(key=lambda item: (-item[0], item[1].category.lower(), item[1].mid, item[1].slug.lower()))
        out[key] = [
            {
                "score": score,
                "mid": tp.mid,
                "slug": tp.slug,
                "category": tp.category,
                "tp_name": tp.tp_name,
                "showroom_url": tp.showroom_url,
            }
            for score, tp in scored[:top_n]
        ]
    return out


def load_seed(path: Path) -> dict[str, Any]:
    raw = json.loads(path.read_text(encoding="utf-8"))
    if isinstance(raw, dict) and isinstance(raw.get("cars"), dict):
        raw.setdefault("unsupported", {})
        return raw
    if isinstance(raw, dict):
        return {"schema_version": 1, "cars": raw, "unsupported": {}}
    raise RuntimeError("Seed JSON is not an object")


def save_seed(path: Path, seed: dict[str, Any], backup_done: bool) -> bool:
    if not backup_done and path.exists():
        backup = path.with_suffix(path.suffix + ".bak")
        if not backup.exists():
            shutil.copy2(path, backup)
        backup_done = True
    _safe_json_dump(path, seed)
    return backup_done


def prompt_choice(pending_index: int, pending_total: int, key: str, car: IRacingCar, candidates: list[dict[str, Any]]) -> str:
    print()
    print("=" * 88)
    print(f"[{pending_index}/{pending_total}] {car.iracing_name}")
    print(f"Key: {key}")
    print(f"Filepath: {car.filepath_full}")
    print("-" * 88)
    if candidates:
        print("Candidates:")
        for idx, cand in enumerate(candidates, start=1):
            print(
                f"  {idx+1}. {cand['tp_name']}  |  {cand['category']}/{cand['mid']}/{cand['slug']}  |  score {cand['score']}"
            )
    else:
        print("No candidate matches above the minimum score were found.")
    print("-" * 88)
    print("Actions:")
    print("  1 = mark as unsupported in Trading Paints")
    if candidates:
        print(f"  2 = accept best match ({candidates[0]['tp_name']})")
        if len(candidates) > 1:
            print(f"  3..{len(candidates)+1} = accept another shown candidate")
    print("  s = skip for now")
    print("  q = save and quit")
    return input("Choose: ").strip().lower()


def review_seed(seed: dict[str, Any], cars: dict[str, IRacingCar], candidates_map: dict[str, list[dict[str, Any]]], seed_path: Path, report_dir: Path) -> None:
    mapped = set((seed.get("cars") or {}).keys())
    unsupported = set((seed.get("unsupported") or {}).keys())

    pending_keys = [k for k in sorted(cars) if k not in mapped and k not in unsupported]
    skipped: dict[str, Any] = {}
    backup_done = False

    if not pending_keys:
        print("No pending cars. Everything from the current iRacing list is already mapped or unsupported.")
        return

    for idx, key in enumerate(pending_keys, start=1):
        car = cars[key]
        cands = candidates_map.get(key, [])
        while True:
            choice = prompt_choice(idx, len(pending_keys), key, car, cands)
            if choice == "q":
                backup_done = save_seed(seed_path, seed, backup_done)
                if skipped:
                    _safe_json_dump(report_dir / "review_skipped.json", skipped)
                print("Saved and quit.")
                return
            if choice == "s":
                skipped[key] = {
                    "iracing_name": car.iracing_name,
                    "top_candidates": cands,
                }
                break
            if choice == "1":
                seed.setdefault("unsupported", {})[key] = {
                    "iracing_name": car.iracing_name,
                    "status": "unsupported_in_tp",
                    "source": "manual_cli_review",
                }
                mapped.discard(key)
                unsupported.add(key)
                backup_done = save_seed(seed_path, seed, backup_done)
                print(f"Marked unsupported: {key}")
                break
            if choice.isdigit():
                raw_num = int(choice)
                if cands and raw_num >= 2 and raw_num <= len(cands) + 1:
                    cand = cands[raw_num - 2]
                    seed.setdefault("cars", {})[key] = {
                        "mid": int(cand["mid"]),
                        "slug": str(cand["slug"]),
                        "category": str(cand["category"]),
                        "tp_name": str(cand["tp_name"]),
                        "iracing_name": car.iracing_name,
                        "status": "mapped",
                        "source": "manual_cli_review",
                    }
                    unsupported.discard(key)
                    mapped.add(key)
                    backup_done = save_seed(seed_path, seed, backup_done)
                    print(f"Mapped: {key} -> {cand['category']}/{cand['mid']}/{cand['slug']}")
                    break
            print("Invalid choice. Try again.")

    if skipped:
        _safe_json_dump(report_dir / "review_skipped.json", skipped)
    else:
        skipped_path = report_dir / "review_skipped.json"
        if skipped_path.exists():
            skipped_path.unlink()
    backup_done = save_seed(seed_path, seed, backup_done)
    print("Review complete and seed saved.")


def parse_args() -> argparse.Namespace:
    p = argparse.ArgumentParser(description="Review only new/pending TP showroom mappings against an existing seed.")
    p.add_argument("--seed", required=True, help="Path to the current seed JSON (for example tp_showroom_mapping.seed.autopromoted.json).")
    p.add_argument("--iracing-source", default=IRACING_ACTIVE_CARS_URL, help="Official iRacing active-car list URL or a local HTML/TXT/JSON file.")
    p.add_argument("--timeout", type=float, default=25.0, help="HTTP timeout in seconds.")
    p.add_argument("--sleep", type=float, default=0.15, help="Pause between TP showroom requests.")
    p.add_argument("--top-n", type=int, default=5, help="How many candidate matches to show per pending car.")
    p.add_argument("--report-dir", default=None, help="Optional directory for cached scan results and skipped report.")
    return p.parse_args()


def main() -> int:
    args = parse_args()
    seed_path = Path(args.seed)
    if not seed_path.exists():
        raise SystemExit(f"Seed file not found: {seed_path}")

    seed = load_seed(seed_path)
    print("Loading iRacing active cars...")
    cars = parse_iracing_active_cars(args.iracing_source, timeout=args.timeout)
    print(f"Loaded {len(cars)} iRacing active cars.")

    print("Scanning Trading Paints showroom catalog (Road + Oval)...")
    catalog = parse_tp_showroom_catalog(timeout=args.timeout, sleep_seconds=args.sleep)
    print(f"Loaded {len(catalog)} Trading Paints showroom car entries.")

    print("Scoring candidate matches...")
    candidates_map = build_candidates(cars, catalog, top_n=max(1, int(args.top_n)))
    print("Done.")

    report_dir = Path(args.report_dir) if args.report_dir else seed_path.parent / "tp_seed_review_output"
    report_dir.mkdir(parents=True, exist_ok=True)

    # Cache helpful artifacts for future review.
    _safe_json_dump(
        report_dir / "iracing_active_cars_parsed.json",
        {
            "schema_version": 1,
            "source": args.iracing_source,
            "count": len(cars),
            "cars": {
                k: {
                    "iracing_name": v.iracing_name,
                    "filepath_full": v.filepath_full,
                    "directory_leaf": v.directory_leaf,
                }
                for k, v in cars.items()
            },
        },
    )
    _safe_json_dump(
        report_dir / "tp_showroom_catalog.json",
        {
            "schema_version": 1,
            "source_pages": list(TP_SHOWROOM_ROOTS),
            "count": len(catalog),
            "categories_included": sorted(TP_CAR_SHOWROOM_CATEGORIES),
            "vehicles": [
                {
                    "mid": v.mid,
                    "category": v.category,
                    "slug": v.slug,
                    "tp_name": v.tp_name,
                    "showroom_url": v.showroom_url,
                }
                for v in catalog
            ],
        },
    )
    _safe_json_dump(
        report_dir / "tp_showroom_candidates.json",
        {
            "schema_version": 1,
            "count": len(candidates_map),
            "candidates": candidates_map,
        },
    )

    print()
    mapped_count = len(seed.get("cars") or {})
    unsupported_count = len(seed.get("unsupported") or {})
    pending_count = sum(1 for k in cars if k not in (seed.get("cars") or {}) and k not in (seed.get("unsupported") or {}))
    print(f"Seed currently has {mapped_count} mapped cars and {unsupported_count} unsupported cars.")
    print(f"Pending cars to review right now: {pending_count}")

    review_seed(seed, cars, candidates_map, seed_path, report_dir)
    return 0


if __name__ == "__main__":
    raise SystemExit(main())
